import numpy as np  # Numerical computing (used 6 times)
import pandas as pd  # Data manipulation (used 6 times)
import matplotlib.pyplot as plt  # Plotting (used 6 times)
import geopandas as gpd  # Geospatial data (used 2 times)
import osmnx as ox  # Street networks (used 2 times)
import scipy.stats  # Statistical functions (used 2 times)
import sklearn  # Machine learning (used 1 time)
import collections  # Specialized data structures like defaultdict (used 1 time)
import pysal  # Spatial data analysis (used 1 time)
